# Prereqs:
#     Run ./bootstrap.sh
#
# Then you can run this playbook with:
#     ansible-playbook -Kv playbook.yml
#
# Ansible User Guide:
#    https://docs.ansible.com/ansible/latest/user_guide/index.html
# Ansible "plugin" index:
#    https://docs.ansible.com/ansible/latest/collections/all_plugins.html
#

- hosts: localhost

  tasks:
  - name: install wget with Homebrew
    homebrew:
      name: wget

  - name: install Mac App Store CLI
    homebrew:
      name: mas

  - name: install apps from Mac App Store
    shell: "mas list | grep \"{{ item }}\" || mas search \"{{ item }}\" | grep \"{{ item }}\" | head -n 1 | awk '{print $1}' | xargs mas install"
    args:
        executable: /bin/bash
    with_items:
      - Amphetamine

  - name: Make hidden files visible
    osx_defaults:
      domain: com.apple.finder
      key: AppleShowAllFiles
      type: bool
      value: true
      state: present
    register: default_set_visible

  - name: Make all extensions visible
    osx_defaults:
      domain: NSGlobalDomain
      key: AppleShowAllExtensions
      type: bool
      value: true
      state: present
    register: default_set_extension

  - name: restart Finder
    command: killall Finder
    when: default_set_visible.changed or default_set_extension.changed
