
- name: add HOMEBREW_GITHUB_API_TOKEN
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.paths_homes_etc"
    line: "export HOMEBREW_GITHUB_API_TOKEN={{ github_api_token }}"
    regexp: "export HOMEBREW_GITHUB_API_TOKEN"

- name: Make sure we can get to older versions
  homebrew_tap:
    name: homebrew/cask-versions

# - name: update homebrew and upgrade brews
#   homebrew:
#     update_homebrew: yes
#     upgrade_all: yes
