- name: Tap fonts
  homebrew_tap:
    name: homebrew/cask-fonts
  when: ansible_system == 'Darwin'

- name: Tap non-free fonts
  homebrew_tap:
    name: colindean/fonts-nonfree
  when: ansible_system == 'Darwin'

- name: Install Microsofts and Fira Code font
  homebrew_cask:
    name: "{{ item }}"
  with_items:
   - font-fira-code
   - font-microsoft-office
  ignore_errors: yes
